namespace: jitsi
svcSuffix: svc.cluster.local

imagePullSecrets:
  - name: regcred

image:
  tag: stable-5390-3
webHost: www.jitsi.otcdemo.gardener.t-systems.net
videoHost: jvb.jitsi.otcdemo.gardener.t-systems.net
# this should be read from istio
publicIp: 80.158.56.57
ingress:
  type: gateway
  annotations: |-
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/ingress.class: istio  
  # sidecar.istio.io/inject: 'true'
  # traffic.sidecar.istio.io/includeInboundPorts: ""
  # traffic.sidecar.istio.io/excludeInboundPorts: "80,443,10000,4443"


common:
  environment:
    - name: ENABLE_XMPP_WEBSOCKET
      value: "0"
    - name: ENABLE_GUESTS
      value: "1"
    - name: ENABLE_AUTH
      value: "0"
    - name: ENABLE_IPV6
      value: "false"
    - name: ENABLE_STATISTICS
      value: "true"
    - name: XMPP_DOMAIN
      value: jitsi.otc
    - name: XMPP_AUTH_DOMAIN
      value: auth.jitsi.otc
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.jitsi.otc
    - name: XMPP_MUC_DOMAIN
      value: muc.jitsi.otc
    - name: XMPP_GUEST_DOMAIN
      value: guest.jitsi.otc
    - name: XMPP_TURN_DOMAIN
      value: turn.jitsi.otc
    - name: JVB_BREWERY_MUC
      value: jvbbrewery
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "false"
    - name: TZ
      value: Europe/Amsterdam
    - name: JVB_ADMINS
      value: "\"jvb@auth.jitsi.otc\",\"focus@auth.jitsi.otc\""
    - name: MARKER
      value: "otc_config"

jicofo:
  userAuth:
    enabled: true
    name: "focus"
    secret: dG90bw==
  componentSecret: dG90bw==
  environment:
    - name: LOG_LEVEL
      value: info
  image:
    repository: jitsi/jicofo
    pullPolicy: IfNotPresent

jvb:
  ingress:
    enabled: false
    annotations: |-
      sidecar.istio.io/inject: 'true'
    # traffic.sidecar.istio.io/includeInboundPorts: ""
    # traffic.sidecar.istio.io/excludeInboundPorts: "80,443,10000,4443"
  userAuth:
    enabled: true
    name: "jvb"
    secret: dG90bw==
  service:
    type: ClusterIP       # NodePort   # nodeports  30000-32768
  nodeport: 30000
  # used for nodeport calculation
  tcpoffset: 1000
  # default ports for video streams
  udpport: 10000
  tcpport: 4443
  environment:
    - name: LOG_LEVEL
      value: info
    - name: JVB_OPTS
      value: "--apis=xmpp,rest,colibri"
    - name: ENABLE_STATISTICS
      value: "true"
  image:
    repository: jitsi/jvb
    pullPolicy: IfNotPresent

prosody:
  replicaCount: 1
  userAuth:
    enabled: true
    guest: 1
    type: internal
  service:
    type: ClusterIP
  environment:
    - name: LOG_LEVEL
      value: info
    - name: XMPP_MUC_MODULES
      value: "muc_meeting_id"
  image:
    repository: jitsi/prosody
    pullPolicy: IfNotPresent

turn:
  enabled: false
  replicaCount: 1
  turnHost: stun.t-online.de
#  turnHost: turn.jitsi.otcdemo.gardener.t-systems.net
  xmppTurnDomain: turn.jitsi.otc

#  externalIp: 80.158.56.57
  extTlsPort: 443
  udpPort: 3478
  tcpPort: 3478
  tlsPort: 5349
  # ports for turn forwarding
  minPort: 10000
  maxPort: 10100
  userAuth:
    enabled: true
    name: tina
    secret: eike
  service:
    type: ClusterIP    
  image:
    # repository: flaviostutz/coturn
    # tag: 4.5.0.5
    repository: instrumentisto/coturn
    tag: 4.5.2
    pullPolicy: IfNotPresent

web:
  replicaCount: 1
  # the letsencrypt script is not working inside the nodes of our helm chart
  # we are using istio in gardener instead
  environment:
    - name: ENABLE_LETSENCRYPT
      value: false
    - name: LETSENCRYPT_DOMAIN
      value: xxxx
    - name: LOG_LEVEL
      value: info
  service:
    type: ClusterIP
    port: 80
    sslport: 443
    annotations: []
  image:
    repository: jitsi/web
    pullPolicy: IfNotPresent
