namespace: jitsi
svcSuffix: svc.cluster.local

imagePullSecrets:
  - name: regcred

image:
  tag: stable-5390-3
webHost: www.jitsi.otcdemo.gardener.t-systems.net
videoHost: jvb.jitsi.otcdemo.gardener.t-systems.net
# this should be read from istio
publicIp: 80.158.56.57
ingress:
  type: ingress
  annotations: |-
    sidecar.istio.io/inject: "true"  
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/ingress.class: istio  
  # sidecar.istio.io/inject: 'true'
  # traffic.sidecar.istio.io/includeInboundPorts: ""
  # traffic.sidecar.istio.io/excludeInboundPorts: "80,443,10000,4443"


common:
  environment:
    - name: ENABLE_XMPP_WEBSOCKET
      value: "0"    
    - name: ENABLE_LETSENCRYPT
      value: "0"
    - name: ENABLE_AUTH
      value: "0"
    - name: LETSENCRYPT_DOMAIN
      value: xxxx
    - name: XMPP_DOMAIN
      value: jitsi.otc
    - name: XMPP_AUTH_DOMAIN
      value: auth.jitsi.otc
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.jitsi.otc
    - name: XMPP_MUC_DOMAIN
      value: muc.jitsi.otc
    - name: XMPP_GUEST_DOMAIN
      value: guest.jitsi.otc
    - name: XMPP_TURN_DOMAIN
      value: turn.jitsi.otc
    - name: JVB_BREWERY_MUC
      value: jvbbrewery      
    - name: JVB_ADMINS
      value: "\"jvb@auth.jitsi.otc\",\"focus@auth.jitsi.otc\""
    - name: TZ
      value: Europe/Amsterdam

jicofo:
  userAuth:
    enabled: false
    name: "focus"
    secret: dG90bw==
  componentSecret: dG90bw==
  environment:
    - name: LOG_LEVEL
      value: info
    - name: JICOFO_ENABLE_HEALTH_CHECKS
      value: "true"      
  image:
    repository: jitsi/jicofo
    pullPolicy: IfNotPresent

jvb:
  ingress:
    enabled: false
    annotations: |-
      sidecar.istio.io/inject: "true"
    # traffic.sidecar.istio.io/includeInboundPorts: ""
    # traffic.sidecar.istio.io/excludeInboundPorts: "80,443,10000,4443"
  userAuth:
    enabled: false
    name: "jvb"
    secret: dG90bw==
  service:
    type: ClusterIP       # NodePort   # nodeports  30000-32768
#    annotations: |-
#      sidecar.istio.io/inject: 'true'
  nodeport: 30000
  # used for nodeport calculation
  tcpoffset: 1000
  # default ports for video streams
  udpport: 10000
  tcpport: 4443
  environment:
    - name: LOG_LEVEL
      value: info
    - name: JVB_OPTS
      value: "--apis=xmpp,rest,colibri"
    - name: ENABLE_STATISTICS
      value: "true"
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "false"
    - name: JVB_STUN_SERVERS
      value: "stun.t-online.de:3478"
    # value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302

  image:
    repository: jitsi/jvb
    pullPolicy: IfNotPresent

prosody:
  replicaCount: 1
  userAuth:
    enabled: false
    guest: 1
    type: internal
  service:
    type: ClusterIP
  environment:
    - name: LOG_LEVEL
      value: info
    - name: ENABLE_GUESTS
      value: "1"
    - name: ENABLE_IPV6
      value: "false"
    - name: ENABLE_STATISTICS
      value: "true"
    - name: TURN_USER
      value: tina
    - name: TURN_PASSWORD
      value: eike
    - name: TURN_HOST
      value: stun.t-online.de
#  turnHost: turn.jitsi.otcdemo.gardener.t-systems.net
    - name: TURN_TCP_PORT
      value: 3478
    - name: TURN_UDP_PORT
      value: 3478
    - name: TURN_TLS_PORT
      value: 5349


  image:
    repository: jitsi/prosody
    pullPolicy: IfNotPresent

turn:
  enabled: false
  replicaCount: 1
  xmppTurnDomain: turn.jitsi.otc
  # ports for turn forwarding
  minPort: 10000
  maxPort: 10100
  userAuth:
    enabled: true
    name: tina
    secret: eike
  service:
    type: ClusterIP    
  image:
    # repository: flaviostutz/coturn
    # tag: 4.5.0.5
    repository: instrumentisto/coturn
    tag: 4.5.2
    pullPolicy: IfNotPresent

web:
  replicaCount: 1
  # the letsencrypt script is not working inside the nodes of our helm chart
  # we are using istio in gardener instead
  environment:
    - name: ENABLE_GUESTS
      value: "1"
    - name: ENABLE_IPV6
      value: "false"
    - name: ENABLE_HTTP_REDIRECT
      value: "0"
    - name: LOG_LEVEL
      value: info
  service:
    type: ClusterIP
    port: 80
    sslport: 443
    annotations: |-
      sidecar.istio.io/inject: 'true'
  image:
    repository: jitsi/web
    pullPolicy: IfNotPresent
