namespace: jitsi

imagePullSecrets:
    - name: regcred

webHost: www.jitsi.otcdemo.gardener.t-systems.net
ip: 80.158.56.57
common:
  environment:
    - name: ENABLE_XMPP_WEBSOCKET
      value: "0"
    - name: ENABLE_GUESTS
      value: "1"
    - name: ENABLE_AUTH
      value: "0"
    - name: ENABLE_STATISTICS
      value: "1"
    - name: LOG_LEVEL
      value: debug
    - name: XMPP_DOMAIN
      value: jitsi.otc
    - name: XMPP_AUTH_DOMAIN
      value: auth.jitsi.otc
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.jitsi.otc
    - name: XMPP_MUC_DOMAIN
      value: muc.jitsi.otc
    - name: XMPP_GUEST_DOMAIN
      value: guest.jitsi.otc
    - name: JVB_BREWERY_MUC
      value: jvbbrewery
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "true"
    - name: TZ
      value: Europe/Amsterdam
    - name: JVB_ADMINS
      value: "\"focus@jitsi.otc\",\"focus@auth.jitsi.otc\""
    - name: MARKER
      value: "otc_config"

web:
  image:
    repository: jitsi/web
    tag: stable-5390-2
  # ingress:
  #   enabled: true
  #   annotations:
      # ingress.kubernetes.io/auth: "oauth2_proxy"
      # ingress.kubernetes.io/oauth-uri-prefix: "/oauth2"
      # ingress.kubernetes.io/forwarded-for: "enabled"
      # ingress.kubernetes.io/load-balance: "uri"
      # ingress.kubernetes.io/ssl-redirect: "ON"
      # ingress.kubernetes.io/ssl-certificate: jitsi-meet-web
      # ingress.kubernetes.io/timeout-tunnel: 3h
      # kubernetes.io/ingress.class: "nginx"
      # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

      # ingress.kubernetes.io/auth: "oauth2_proxy"
      # ingress.kubernetes.io/oauth-uri-prefix: "/oauth2"
      # ingress.kubernetes.io/forwarded-for: "enabled"
      # ingress.kubernetes.io/load-balance: "uri"
      # ingress.kubernetes.io/ssl-redirect: "ON"
      # ingress.kubernetes.io/ssl-certificate: jitsi-meet-web
      # ingress.kubernetes.io/timeout-tunnel: 3h
      # kubernetes.io/ingress.class: "haproxy"    
  #   hosts:
  #     - host: www.jitsi.otcdemo.gardener.t-systems.net
  #       oauth: true
  #       paths:
  #         - /
  #   tls:
  #     - hosts:
  #         - tls.jitsi.otcdemo.gardener.t-systems.net
  #       secretName: ssl-jitsi-cert-tls

  # # this is not working in our helm chart since it depends on unix versions and scripting
  # we are using istio and gardener now
  environment:
    - name: ENABLE_LETSENCRYPT
      value: false
    - name: LETSENCRYPT_DOMAIN
      value: xxxx
  replicaCount: 1
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: memory
          targetAverageUtilization: 70
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 70      
  service:
    annotations: []
    type: istio
    port: 80
    sslport: 443
 
jicofo:
  image:
    repository: jitsi/jicofo
    tag: stable-5390-2
  userAuth:
    enabled: true
    name: "focus"
    secret: dG90bw==
  componentSecret: dG90bw==

jvb:
  image:
    repository: jitsi/jvb
    tag: stable-5390-2
  userAuth:
    enabled: true
    name: "jvb"
    secret: dG90bw==
  baseport: 30300
  tcpoffset: 10000
  udport: 10000
  tcpport: 4443
  environment:
    - name: JVB_STUN_SERVERS
      value: meet-jit-si-turnrelay.jitsi.net:443 
#      value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
    - name: DOCKER_HOST_ADDRESS
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP

prosody:
  replicaCount: 1
  auth:
    enabled: true
    guest: 1
# service    
#    type: internal
  image:
    repository: jitsi/prosody
    tag: stable-5390-2
    pullPolicy: IfNotPresent

