namespace: jitsi

imagePullSecrets:
    - name: regcred

webHost: www.jitsi.otcdemo.gardener.t-systems.net

common:
  environment:
    - name: ENABLE_XMPP_WEBSOCKET
      value: "0"
    - name: ENABLE_GUESTS
      value: "1"
    - name: ENABLE_AUTH
      value: "0"
    - name: LOG_LEVEL
      value: debug
    - name: XMPP_DOMAIN
      value: jitsi.otcdemo.gardener.t-systems.net
    - name: XMPP_AUTH_DOMAIN
      value: auth.jitsi.otcdemo.gardener.t-systems.net
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.jitsi.otcdemo.gardener.t-systems.net
    - name: XMPP_MUC_DOMAIN
      value: muc.jitsi.otcdemo.gardener.t-systems.net
    - name: XMPP_GUEST_DOMAIN
      value: guest.jitsi.otcdemo.gardener.t-systems.net
    - name: JVB_BREWERY_MUC
      value: jvbbrewery
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "true"
    - name: TZ
      value: Europe/Amsterdam
    - name: JVB_ADMINS
      value: "\"focus@jitsi.otcdemo.gardener.t-systems.net\",\"focus@auth.jitsi.otcdemo.gardener.t-systems.net\""
   - name: MARKER
      value: "otc_config"

web:
  image:
    repository: jitsi/web
    tag: stable-5390-2
  ingress:
    enabled: true
    annotations:
      # - name: cert-manager.io/issuer
      #   value: "letsencrypt"
      # - name: cert-manager.io/cluster-issuer
      #   value: "letsencrypt"
      # - name: cert-manager.io/private-key
      #   value: "letsencrypt"
      # - name: cert-manager.io/acme-challenge-type
      #   value: http01
      # - name: kubernetes.io/ingress.class
      #   value: "nginx"
      # - name: nginx.ingress.kubernetes.io/force-ssl-redirect
      #   value: "true"

      cert-manager.io/cluster-issuer: "letsencrypt"
      cert-manager.io/acme-challenge-type: http01
      ingress.kubernetes.io/auth: "oauth2_proxy"
      ingress.kubernetes.io/oauth-uri-prefix: "/oauth2"
      ingress.kubernetes.io/forwarded-for: "enabled"
      ingress.kubernetes.io/load-balance: "uri"
      ingress.kubernetes.io/ssl-redirect: "ON"
      ingress.kubernetes.io/ssl-certificate: jitsi-meet-web
      ingress.kubernetes.io/timeout-tunnel: 3h
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

      # ingress.kubernetes.io/auth: "oauth2_proxy"
      # ingress.kubernetes.io/oauth-uri-prefix: "/oauth2"
      # ingress.kubernetes.io/forwarded-for: "enabled"
      # ingress.kubernetes.io/load-balance: "uri"
      # ingress.kubernetes.io/ssl-redirect: "ON"
      # ingress.kubernetes.io/ssl-certificate: jitsi-meet-web
      # ingress.kubernetes.io/timeout-tunnel: 3h
      # kubernetes.io/ingress.class: "haproxy"    
    hosts:
      - host: jitsi.otcdemo.gardener.t-systems.net
        oauth: true
        paths:
          - /
    tls:
      - hosts:
          - jitsi.otcdemo.gardener.t-systems.net
        secretName: ssl-jitsi-cert-tls
  # this is not working in our helm chart since it depends on unix versions and scripting
  environment:
    - name: ENABLE_LETSENCRYPT
      value: false
    - name: LETSENCRYPT_DOMAIN
      value: jitsi.otcdemo.gardener.t-systems.net      
  replicaCount: 1
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: memory
          targetAverageUtilization: 70
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 70      
  service:
    annotations: []
    type: LoadBalancer
    port: 80
    sslport: 443
  # jwtsidecar:
  #   extraArgs:
  #     provider: oidc
  #     email-domain: "*"
  #     provider-display-name: auth0
  #     client-id: IJ9cjGKL1b410N5QpkI36pNbJ7khJFvu
  #     client-secret: Napkyd1t_JuTMJnyQZvRLTq_6xncAxI6ZKuDMUsVyOiSec9Qj-5kYFvGPhyIbPLJ
  #     insecure-oidc-allow-unverified-email: true
  #     oidc-issuer-url: https://gardener-demo.eu.auth0.com/
  #     oidc-jwks-url:  https://gardener-demo.eu.auth0.com/.well-known/jwks.json
  #     cookie-secure: true
  #     cookie-domain: jitsi.otcdemo.gardener.t-systems.net
  #     scope: "cgr_9RGm7rM4ooq1k87C"
  #     cookie-secure: true
  #     cookie-domain: otcdemo.gardener.t-systems.net
  #     cookie-secret: randomcookiesecr
  #     cookie-samesite: lax
  #     set-xauthrequest: true
  #     proxy-prefix: "/oauth2"

jicofo:
  image:
    repository: jitsi/jicofo
    tag: stable-5390-2
  userAuth:
    enabled: true
    name: "focus"
    secret: dG90bw==
  componentSecret: dG90bw==

jvb:
  image:
    repository: jitsi/jvb
    tag: stable-5390-2
  userAuth:
    enabled: true
    name: "jvb"
    secret: dG90bw==
  environment:
    - name: JVB_STUN_SERVERS
      value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
    - name: DOCKER_HOST_ADDRESS
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP

prosody:
  auth:
    enabled: true
    guest: 1
#     
    type: internal
  image:
    repository: jitsi/prosody
    tag: stable-5390-2
    pullPolicy: IfNotPresent

