namespace: jitsi

imagePullSecrets:
    - name: regcred

webHost: www.jitsi.otcdemo.gardener.t-systems.net
ip: 80.158.56.57
common:
  environment:
    - name: ENABLE_XMPP_WEBSOCKET
      value: "0"
    - name: ENABLE_GUESTS
      value: "1"
    - name: ENABLE_AUTH
      value: "0"
    - name: ENABLE_STATISTICS
      value: "1"
    - name: XMPP_DOMAIN
      value: jitsi.otc
    - name: XMPP_AUTH_DOMAIN
      value: auth.jitsi.otc
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.jitsi.otc
    - name: XMPP_MUC_DOMAIN
      value: muc.jitsi.otc
    - name: XMPP_GUEST_DOMAIN
      value: guest.jitsi.otc
    - name: JVB_BREWERY_MUC
      value: jvbbrewery
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "true"
    - name: TZ
      value: Europe/Amsterdam
    - name: JVB_ADMINS
      value: "\"focus@jitsi.otc\",\"focus@auth.jitsi.otc\""
    - name: MARKER
      value: "otc_config"

web:
  image:
    repository: jitsi/web
    tag: stable-5390-2
  # the letsencrypt script is not working inside the nodes of our helm chart 
  # we are using istio in gardener instead
  environment:
    - name: ENABLE_LETSENCRYPT
      value: false
    - name: LETSENCRYPT_DOMAIN
      value: xxxx
    - name: LOG_LEVEL
      value: info
  replicaCount: 1
  service:
    annotations: []
    type: istio
    port: 80
    sslport: 443
 
jicofo:
  image:
    repository: jitsi/jicofo
    tag: stable-5390-2
  userAuth:
    enabled: true
    name: "focus"
    secret: dG90bw==
  componentSecret: dG90bw==
  environment:
    - name: LOG_LEVEL
      value: info

jvb:
  image:
    repository: jitsi/jvb
    tag: stable-5390-2
  userAuth:
    enabled: true
    name: "jvb"
    secret: dG90bw==
  baseport: 30300
  tcpoffset: 1000
  udpport: 10000
  tcpport: 4443
  environment:
    - name: LOG_LEVEL
      value: info
    - name: JVB_STUN_SERVERS
      # value: meet-jit-si-turnrelay.jitsi.net:443 
      value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
    # replaced DOCKER_HOST_ADDRESS with PUBLIC_URL_HOST which is more meaningful in k8s
    # - name: DOCKER_HOST_ADDRESS
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: status.hostIP

prosody:
  replicaCount: 1
  auth:
    enabled: true
    guest: 1
  environment:
    - name: LOG_LEVEL
      value: info# service    
#    type: internal
  image:
    repository: jitsi/prosody
    tag: stable-5390-2
    pullPolicy: IfNotPresent

