namespace: jitsi
svcSuffix: svc.cluster.local

imagePullSecrets:
  - name: regcred
image:
  tag: stable-5390-3

#webHost: www.jitsi.otcdemo.gardener.t-systems.net
#publicIp: 80.158.56.57
webHost: ng.jitsi.otcdemo.gardener.t-systems.net
#webHostAlt: jitsing.otcdemo.gardener.t-systems.net
publicIp: 80.158.51.176
ingress:
  # nginx-ingress istio-ingress istio-gateway
  type: nginx-ingress
  annotations: |-
    sidecar.istio.io/inject: "true"

common:
  domain: jitsi.otc
  env:
    - name: ENABLE_XMPP_WEBSOCKET
      value: "0"
    - name: ENABLE_LETSENCRYPT
      value: "0"
    - name: ENABLE_AUTH
      value: "0"
    - name: LETSENCRYPT_DOMAIN
      value: ng.jitsi.otcdemo.gardener.t-systems.net
    - name: JVB_BREWERY_MUC
      value: jvbbrewery
    - name: TZ
      value: Europe/Amsterdam

jicofo:
  userAuth:
    enabled: false
    name: "focus"
    secret: dG90bw==
  componentSecret: dG90bw==
  env:
    - name: LOG_LEVEL
      value: info
    - name: JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS
      value: "true"
    - name: JICOFO_ENABLE_HEALTH_CHECKS
      value: "false"
  image:
    repository: jitsi/jicofo
    pullPolicy: IfNotPresent

jvb:
  ingress:
    enabled: false
    annotations: |-
      sidecar.istio.io/inject: "true"
    # traffic.sidecar.istio.io/includeInboundPorts: ""
    # traffic.sidecar.istio.io/excludeInboundPorts: "80,443,10000,4443"
  userAuth:
    enabled: false
    name: "jvb"
    secret: dG90bw==
  service:
    type: ClusterIP       # NodePort   # nodeports  30000-32768
#    annotations: |-
#      sidecar.istio.io/inject: 'true'
  nodeport: 30000
  # used for nodeport calculation
  tcpoffset: 1000
  # default ports for video streams
  udpport: 10000
  tcpport: 4443
  env:
    - name: LOG_LEVEL
      value: info
    - name: JVB_OPTS
      value: "--apis=xmpp,rest"
    - name: ENABLE_STATISTICS
      value: "true"
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "false"
      # use values from below!!!!!!!!!!!!!
    - name: JVB_STUN_SERVERS
      value: "jitsid.otcdemo.gardener.t-systems.net:38743"
    # value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302

  image:
    repository: jitsi/jvb
    pullPolicy: IfNotPresent

prosody:
  replicaCount: 1
  userAuth:
    enabled: false
    guest: 1
    type: internal
  service:
    type: ClusterIP
  env:
    - name: TURN_HOST
      value: jitsid.otcdemo.gardener.t-systems.net
    - name: TURN_PORT
      value: 38743
    - name: TURNS_PORT
      value: 39435
    - name: TURN_USER
      value: mycoturn
    - name: TURN_PASS
      value: m0recomplicatedPassword
    - name: LOG_LEVEL
      value: info
    - name: ENABLE_GUESTS
      value: "1"
    - name: ENABLE_IPV6
      value: "true"
    - name: ENABLE_STATISTICS
      value: "true"
#    - name: TURN_AUTH_PASSWORD
#      value: mySecretTurnPasswordConfiguredInTurnServer
#      value: meet-jit-si-turnrelay.jitsi.net
#      value: stun.t-online.de
#  turnHost: turn.jitsi.otcdemo.gardener.t-systems.net
    # - name: TURN_PORT
    #   value: 3478
    # - name: TURN_TCP_PORT
    #   value: 3478
    # - name: TURN_UDP_PORT
    #   value: 3478
    # - name: TURN_TLS_PORT
    #   value: 5349


  image:
    repository: jitsi/prosody
    pullPolicy: IfNotPresent

turn:
  enabled: false
  replicaCount: 1
  xmppTurnDomain: turn.jitsi.otc
  # ports for turn forwarding
  minPort: 10000
  maxPort: 10100
  userAuth:
    enabled: true
    name: tina
    secret: eike
  service:
    type: ClusterIP
  image:
    # repository: flaviostutz/coturn
    # tag: 4.5.0.5
    repository: instrumentisto/coturn
    tag: 4.5.2
    pullPolicy: IfNotPresent

web:
  replicaCount: 1
  # the letsencrypt script is not working inside the nodes of our helm chart
  # we are using istio in gardener instead
  env:
    - name: ENABLE_GUESTS
      value: "1"
    - name: ENABLE_IPV6
      value: "false"
    - name: ENABLE_HTTP_REDIRECT
      value: "0"
    - name: LOG_LEVEL
      value: info
    # skip key generation on deployment
    - name: DISABLE_HTTPS
      value: "1"
  service:
    type: ClusterIP
    port: 80
    sslport: 443
    annotations: |-
      sidecar.istio.io/inject: 'true'
  image:
    repository: jitsi/web
    pullPolicy: IfNotPresent
