{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  kubernetes.io/ingress.class: istio  
  name: {{ include "jitsi-meet.name" . }}-ingress
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
  {{- with .Values.jvb.ingress.annotations -}}
  annotations:
    sidecar.istio.io/inject: 'true'
    traffic.sidecar.istio.io/includeInboundPorts: ""
    traffic.sidecar.istio.io/excludeInboundPorts: "80,443,10000,4443"
    {{- toYaml . | nindent 4 }}
  {{- end -}}
spec:
  rules:
    - host: {{ .Values.webHost | quote }}
      tcp:
        port: { .Values.jvb.tcpport }}
        paths:
          - path: {{ . | quote }}
            backend:
              # single port test
              serviceName: {{ include "jitsi-meet.name-jvb" }}-0
              servicePort: {{ .Values.jvb.udpport }}
{{- end -}}  
