{{- if (eq .Values.ingress.type "gateway") -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "jitsi-meet.name-gateway" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
#    app: {{ include "jitsi-meet.name" . }}
  servers:
  # - port:
  #     number: 80
  #     name: http
  #     protocol: HTTP
  #   hosts:
  #   - {{ .Values.webHost }}
  #   tls:
  #     httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - {{ .Values.webHost }}
    tls:
      mode: SIMPLE
      credentialName: wildcard-tls
#      minProtocolVersion: TLSV1_2

# iterate over jvb replicas and assing different ports TODO for now
# TODO THIS IS NOT WORKING !!
{{- $root := . }}
{{- range $index, $nbr := until (.Values.jvb.replicaCount | int) }}
{{- $tcpport := printf "%d" (add $root.Values.jvb.tcpport $nbr) }}
{{- $tcpportname := printf "tcp-%d" $nbr }}
{{- $udpport := printf "%d" (add $root.Values.jvb.udpport $nbr) }}
{{- $udpportname := printf "udp-%d" $nbr }}
  - port:
      number: {{ atoi $tcpport }}
      name: {{ $tcpportname }}
      protocol: TCP
    hosts:
    - "*"       # try wildcard

  - port:
      number: 5555
      name: test-5555
      protocol: TCP
    hosts:
    - "*"       # try wildcard

  # - port:
  #     number: {{ atoi $udpport }}
  #     name: {{ $udpportname }}
  #     protocol: UDP
  #   hosts:
  #   - {{ $root.Values.webHost }}
{{- end }}
{{- end }}
