apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.name-jicofo" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jitsi-meet.name-jicofo" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jitsi-meet.name-jicofo" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "jitsi-meet.name-jicofo" . }}
        image: "{{ .Values.jicofo.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.jicofo.image.pullPolicy }}
        env:
          {{ if .Values.jicofo.userAuth.enabled }}
          - name: JICOFO_AUTH_USER
            value: {{ .Values.jicofo.userAuth.name }}            
          - name: JICOFO_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "jitsi-meet.name-jicofo-secret" . }}
                key: JICOFO_AUTH_PASSWORD
          {{ end }}
          - name: JICOFO_COMPONENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "jitsi-meet.name-jicofo-secret" . }}
                key: JICOFO_COMPONENT_SECRET
          - name: XMPP_SERVER
            value: {{ include "jitsi-meet.name-prosody" . }}
          {{- if .Values.prosody.userAuth.enabled }}
          - name: ENABLE_AUTH
            value: "1"
          {{- end }}
          {{- range .Values.jicofo.environment }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
          {{- end }}
          {{- range .Values.common.environment }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
          {{- end }}
        resources:
          {{- toYaml .Values.jicofo.resources | nindent 12 }}
        # mount config file /var/app and copy to defaults
        volumeMounts:
          - name: config
            mountPath: "/defaults/sip-communicator.properties"
            subPath: "sip-communicator.properties"
      volumes:
        - name: config
          configMap:
            name: {{ template "jitsi-meet.name-jicofo-config" . }}

