apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsi-meet.name-jicofo-secret" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
data:
  JICOFO_AUTH_PASSWORD: {{ .Values.jicofo.userAuth.secret | quote }}
  JICOFO_COMPONENT_SECRET: {{ .Values.jicofo.componentSecret | quote }}
