apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.name-jicofo" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jitsi-meet.name-jicofo" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jitsi-meet.name-jicofo" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "jitsi-meet.name-jicofo" . }}
        image: "{{ .Values.jicofo.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.jicofo.image.pullPolicy }}
        env:
          - name: XMPP_DOMAIN
            value: {{ .Values.common.domain }}
          - name: XMPP_AUTH_DOMAIN
            value: auth.{{ .Values.common.domain }}
          - name: XMPP_INTERNAL_MUC_DOMAIN
            value: internal-muc.{{ .Values.common.domain }}
          - name: XMPP_MUC_DOMAIN
            value: muc.{{ .Values.common.domain }}
          - name: XMPP_GUEST_DOMAIN
            value: guest.{{ .Values.common.domain }}
          - name: JVB_ADMINS
            value: "\"jvb@auth.{{ .Values.common.domain }}\",\"focus@auth.{{ .Values.common.domain }}\""

          - name: JICOFO_AUTH_USER
            value: {{ .Values.jicofo.userAuth.name }}
          - name: JICOFO_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "jitsi-meet.name-jicofo-secret" . }}
                key: JICOFO_AUTH_PASSWORD
          - name: JICOFO_COMPONENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "jitsi-meet.name-jicofo-secret" . }}
                key: JICOFO_COMPONENT_SECRET
          - name: XMPP_SERVER
            value: {{ include "jitsi-meet.name-prosody" . }}
          - name: PUBLIC_URL
            value: "https://{{ .Values.webHost }}"
          {{- range .Values.jicofo.env }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
          {{- end }}
          {{- range .Values.common.env }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
          {{- end }}
        resources:
          {{- toYaml .Values.jicofo.resources | nindent 12 }}
        # mount config file /var/app and copy to defaults
        volumeMounts:
          - name: config
            mountPath: "/defaults/sip-communicator.properties"
            subPath: "sip-communicator.properties"
          - name: config
            mountPath: "/defaults/logging.properties"
            subPath: "logging.properties"
      volumes:
        - name: config
          configMap:
            name: {{ template "jitsi-meet.name-jicofo-config" . }}

