{{- if .Values.jvb.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "jitsi-meet.name-jvb" . }}-ingress
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
  {{- with .Values.jvb.ingress.annotations -}}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end -}}
spec:
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ . | quote }}
            backend:
              # single port test
              serviceName: {{ include "jitsi-meet.name-jvb" }}-0
              servicePort: {{ .Values.jvb.udpport }}
{{- end -}}  
