{{- $basename := include "jitsi-meet.name-jvb" . }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $basename }}-vs
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  hosts:
  - {{ .Values.webHost }}
  gateways:
  - {{ include "jitsi-meet.name" . }}-gateway
# video bridge over tcp 
  tcp:
# iterate over replica and assing different ports
{{- $root := . }}
{{- range $index, $nbr := until (.Values.jvb.replicaCount | int) }}
{{- $target := printf "%s-%d" $basename $nbr}}
{{- $udpport := printf "%d" (add $root.Values.jvb.udpport $nbr) }}
{{- $tcpport := printf "%d" (add $root.Values.jvb.tcpport $nbr) }}
#---------------------------------------------------
  - match:
    - port: {{ atoi $tcpport }}
    route:
    - destination:
        host: {{ $target }}
        port:
          number: {{ atoi $tcpport }}
#---------------------------------------------------          
  - match:
    - port: {{ atoi $udpport }}
    route:
    - destination:
        host: {{ $target }}
        port:
          number: {{ atoi $udpport }}
{{- end }}
