{{- $root := . -}}
{{- $name := include "jitsi-meet.name-jvb" $root -}}
{{- range $index, $nbr := until (.Values.prosody.replicaCount | int) }}
{{- $udpport := printf "%d" (add $root.Values.jvb.udpport $nbr) }}
{{- $tcpport := printf "%d" (add $root.Values.jvb.tcpport $nbr) }}
{{- $udpportname := printf "udp-%d" $nbr }}
{{- $tcpportname := printf "tcp-%d" $nbr }}
---
{{- $deployName := printf "%s-%d" $name $nbr -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deployName | quote }}
  namespace: {{ $root.Values.namespace | quote }}
  labels:
{{ include "jitsi-meet.labels" $root | indent 4 }}
spec:
  replicas: {{ $root.Values.jvb.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $deployName | quote }}
      app.kubernetes.io/instance: {{ $root.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $deployName | quote }}
        app.kubernetes.io/instance: {{ $root.Release.Name }}
    spec:
    {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "jitsi-meet.serviceAccountName" $root }}
      securityContext:
        {{- toYaml $root.Values.jvb.securityContext | nindent 8 }}
      containers:
        - name: {{ $name | quote }}
          image: {{ printf "%s:%s" $root.Values.jvb.image.repository $root.Values.image.tag | quote }}
          imagePullPolicy: {{ $root.Values.jvb.image.pullPolicy | quote }}
          command: ["/bin/bash"] 
          # this entrypoint now only installs more packages
          args: ["/entrypoint.sh","/init"]
          securityContext:
            capabilities:
              add:
                - SYS_RESOURCE
                - NET_ADMIN
          {{- with $root.Values.jvb.podSecurityContext }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: JVB_PORT
              value: {{ $udpport | quote }}
            - name: JVB_TCP_PORT
              value: {{ $tcpport | quote }}
            - name: JVB_TCP_MAPPED_PORT
              value: {{ $tcpport | quote }}
            - name: PUBLIC_URL
              value: "https://{{ $root.Values.webHost }}:443"

            # these values are used for the HARVESTER CONFIG              
            # - name: PUBLIC_IP
            #   value: "{{ $root.Values.publicIp }}"
            - name: DOCKER_HOST_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: XMPP_SERVER
              value: {{ include "jitsi-meet.name-prosody" $root }}
            - name: PROSODY_INSTANCE
              value: {{ printf "%d" $nbr | quote }}

            - name: JICOFO_AUTH_USER
              value: {{ $root.Values.jicofo.userAuth.name }}
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "jitsi-meet.name-jicofo-secret" $root }}
                  key: JICOFO_AUTH_PASSWORD
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "jitsi-meet.name-jicofo-secret" $root }}
                  key: JICOFO_COMPONENT_SECRET

            - name: JVB_AUTH_USER
              value: {{ $root.Values.jvb.userAuth.name }}
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "jitsi-meet.name-jvb-secret" $root }}
                  key: JVB_AUTH_PASSWORD
            - name: JVB_ENABLE_APIS
              value: "rest,colibri,xmpp"
            {{- with $root.Values.jvb.environment }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with $root.Values.common.environment }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: {{ $udpportname }}
              containerPort: {{ atoi $udpport }}
              protocol: UDP
            - name: {{ $tcpportname }}
              containerPort: {{ atoi $tcpport }}
              protocol: TCP
            - name: "test-5555"
              containerPort: 5555
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/defaults/jvb.conf"
              subPath: "jvb.conf"
            - name: config
              mountPath: "/defaults/logging.properties"
              subPath: "logging.properties"
            - name: config
              mountPath: "/defaults/sip-communicator.properties"
              subPath: "sip-communicator.properties"
            - name: config
              mountPath: "/entrypoint.sh"
              subPath: "entrypoint.sh"
          resources:
            {{- toYaml $root.Values.jvb.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "jitsi-meet.name-jvb-config" $root }}
    {{- with $root.Values.jvb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $root.Values.jvb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $root.Values.jvb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}