{{- if (eq .Values.ingress.type "gateway") -}}
{{- $basename := include "jitsi-meet.name-jvb" . }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $basename }}-vs
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  hosts:
  - {{ .Values.webHost }}
  gateways:
  - {{ include "jitsi-meet.name-gateway-fqdn" . }}
  # video bridge over tcp 
  tcp:
  # iterate over replica and assing different ports
  {{- $root := . }}
  {{- range $index, $nbr := until (.Values.jvb.replicaCount | int) -}}
  {{- $target := printf "%s-%d.%s.%s" $basename $nbr $root.Values.namespace $root.Values.svcSuffix -}}
  {{- $udpport := printf "%d" (add $root.Values.jvb.udpport $nbr) -}}
  {{- $tcpport := printf "%d" (add $root.Values.jvb.tcpport $nbr) -}}
  #---------------------------------------------------
  - match:
    - port: {{ atoi $tcpport }}
    route:
    - destination:
        host: {{ $target }}
        port:
          number: {{ atoi $tcpport }}
  - match:
    - port: 5555
    route:
    - destination:
        host: {{ $target }}
        port:
          number: 5555
  - match:
    - port: 8080
    route:
    - destination:
        host: {{ $target }}
        port:
          number: 8080
  #---------------------------------------------------          
  # - match:
  #   - port: {{ atoi $udpport }}
  #   route:
  #   - destination:
  #       host: {{ $target }}
  #       port:
  #         number: {{ atoi $udpport }}
  http:
#---------------------------------------------------    
  - match:
    - uri:
        prefix: "/*"
    route:
    - destination:
        host: {{ include "jitsi-meet.name-jvbsvc-fqdn" . }}
        port:
          number: 9090
  {{- end }}
{{- end -}}  