{{- $root := . }}
{{- $name := include "jitsi-meet.name-jvb" $root }}
# iterate over replica and assing different ports
{{- range $index, $nbr := until (.Values.prosody.replicaCount | int) }}
{{- $port := printf "%s%s" "3030" (toString $nbr) }}
{{- $target := printf "%s-%d" $name $nbr}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $target | quote }}
  namespace: {{ .Values.namespace }}
labels:
{{ include "jitsi-meet.labels" $root | indent 4 }}
  {{- with $root.Values.jvb.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  sessionAffinity: {{ $root.Values.jvb.service.sessionAffinity }}
  {{- if $root.Values.jvb.service.sessionAffinityConfig }}
  {{- toYaml $root.Values.jvb.service.sessionAffinityConfig }}
  {{- end }}
  ports:
  - name: first
    port: {{ atoi $port }}
    nodePort: {{ atoi $port }}
    protocol: UDP
    targetPort: {{ atoi $port }}
  - name: udp
    port: 30000
    nodePort: 30000
    protocol: UDP
    targetPort: 30000
  - name: tcp
    port: 30001
    nodePort: 30001
    protocol: TCP
    targetPort: 30001
    
  selector:
    app.kubernetes.io/name: {{ $target | quote }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    service: {{ $target | quote }}
{{- end }}