apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jitsi-meet.name-jvb-config" . }}-cm
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
data:
  sip-communicator.properties: |-
    {{- .Files.Get "configs/jvb/sip-communicator.properties" | nindent 4 }}
  logging.properties: |-
    {{- .Files.Get "configs/jvb/logging.properties" | nindent 4 }}
  jvb.conf: |-
    {{- .Files.Get "configs/jvb/jvb.conf" | nindent 4 }}
  entrypoint.sh: |-
    {{- .Files.Get "configs/jvb/entrypoint.sh" | nindent 4 }}

