# iterate over replica and assing different ports
{{- $root := . }}
{{- $name := include "jitsi-meet.name-jvb" $root }}
{{- $tcpoffset := .Values.jvb.tcpoffset }}
{{- range $index, $nbr := until (.Values.prosody.replicaCount | int) }}
{{- $target := printf "%s-%d" $name $nbr}}
{{- $udpport := printf "%d" (add $root.Values.jvb.udpport $nbr) }}
{{- $tcpport := printf "%d" (add $root.Values.jvb.tcpport $nbr) }}

{{- $udpnodeport := printf "%d" (add $root.Values.jvb.nodeport $nbr) }}
{{- $tcpnodeport := printf "%d" (add $root.Values.jvb.nodeport $tcpoffset $nbr)  }}

{{- $udpportname := printf "udp-%d" $nbr }}
{{- $tcpportname := printf "tcp-%d" $nbr }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $target | quote }}
  namespace: {{ $root.Values.namespace | quote }}
  labels:
{{ include "jitsi-meet.labels" $root | indent 4 }}
  {{- with $root.Values.jvb.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  sessionAffinity: {{ $root.Values.jvb.service.sessionAffinity }}
  {{- if $root.Values.jvb.service.sessionAffinityConfig }}
  {{- toYaml $root.Values.jvb.service.sessionAffinityConfig }}
  {{- end }}
  ports:
  - port: {{ atoi $udpport }}
    name: {{ $udpportname }}
    nodePort: {{ atoi $udpnodeport }}
    protocol: UDP
    targetPort: udpvideo

  - port: {{ atoi $tcpport}}
    name: {{ $tcpportname }}
    nodePort: {{ atoi $tcpnodeport }}
    protocol: TCP
    targetPort: tcpvideo

  selector:
    app.kubernetes.io/name: {{ $target | quote }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    service: {{ $target | quote }}
{{- end }}
