{{- if (eq .Values.ingress.type "nginx-ingress") -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "jitsi-meet.name" . }}-nginx-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  tls:
    - hosts:
      - {{ .Values.webHost }}
      - {{ .Values.webHostAlt }}
      secretName: wildcard-tls  # copied from istio to this NS
  rules:
    - host: {{ .Values.webHost }}
      http:
        paths:
          - path: /never
            pathType: Prefix
            backend:
              serviceName: {{ include "jitsi-meet.name-prosody" . }}
              servicePort: 5280
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ include "jitsi-meet.name-web" . }}
              servicePort: {{ .Values.web.service.port }}
    - host: {{ .Values.webHostAlt }}
      http:
        paths:
          - path: /never
            pathType: Prefix
            backend:
              serviceName: {{ include "jitsi-meet.name-prosody" . }}
              servicePort: 5280
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ include "jitsi-meet.name-web" . }}
              servicePort: {{ .Values.web.service.port }}

{{- end -}}