{{- if (eq .Values.ingress.type "nginx-ingress") -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "jitsi-meet.name" . }}-nginx-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/websocket-services : {{ include "jitsi-meet.name-prosody" . }},{{ include "jitsi-meet.name-jvb" . }}-0
    nginx.org/websocket-services : {{ include "jitsi-meet.name-prosody" . }},{{ include "jitsi-meet.name-jvb" . }}-0
#    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"

#    nginx.ingress.kubernetes.io/configuration-snippet: |
#      more_set_headers "proxy_read_timeout: 3600";
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  tls:
    - hosts:
      - {{ .Values.webHost }}
      secretName: wildcard-tls  # copied from istio to this NS
  rules:
    - host: {{ .Values.webHost }}
      http:
        paths:
          - path: /http-bind
            pathType: Prefix
            backend:
              serviceName: {{ include "jitsi-meet.name-prosody" . }}
              servicePort: 5280

          - path: /xmpp-websocket/
            pathType: Prefix
            backend:
              serviceName: {{ include "jitsi-meet.name-prosody" . }}
              servicePort: 5280

          - path: /colibri-ws/
            pathType: Prefix
            backend:
              serviceName: {{ include "jitsi-meet.name-jvb" . }}-0
              servicePort: 9090

          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ include "jitsi-meet.name-web" . }}
              servicePort: {{ .Values.web.service.port }}

{{- end -}}