apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.name-prosody-config" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
data:
  prosody.cfg.lua: |-
    {{- .Files.Get "configs/prosody/prosody.cfg.lua" | nindent 4 }}
  jitsi-meet.cfg.lua: |-
    {{- .Files.Get "configs/prosody/jitsi-meet.cfg.lua" | nindent 4 }}
  # turn.cfg.lua: |-
  #   {{- .Files.Get "configs/prosody/turn.cfg.lua" | nindent 4 }}
  entrypoint.sh: |-
    {{- .Files.Get "configs/prosody/entrypoint.sh" | nindent 4 }}
