apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.name-prosody" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  type: {{ .Values.prosody.service.type }}
  ports:
    - name: xmpp-client
      port: 5222
      targetPort: xmpp-client
      protocol: TCP

    - name: xmpp-server
      port: 5269
      targetPort: xmpp-server
      protocol: TCP

    - name: xmpp-bosh
      port: 5280
      targetPort: xmpp-bosh
      protocol: TCP

    - name: xmpp-bosh-ssl
      port: 5281
      targetPort: xmpp-bosh-ssl
      protocol: TCP

    - name: prosody-compreg
      port: 5347
      targetPort: prosody-compreg
      protocol: TCP

  sessionAffinity: ClientIP
  selector:
    app.kubernetes.io/name: {{ include "jitsi-meet.name-prosody" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
status:
  loadBalancer: {}
