apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jitsi-meet.name-prosody" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  serviceName: {{ include "jitsi-meet.name-prosody" . }}
  replicas: {{ .Values.prosody.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jitsi-meet.name-prosody" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jitsi-meet.name-prosody" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "jitsi-meet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "jitsi-meet.name-prosody" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.prosody.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.prosody.image.pullPolicy }}
          # this entrypoint now only installs more packages
          command: ["/bin/bash"]
          args: ["/entrypoint.sh","/init"]
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/bash"
                  - "-c"
                  - >
                    "env"
#                    "prosodyctl --config /config/prosody.cfg.lua register me $XMPP_DOMAIN $JVB_AUTH_PASSWORD || true"
          env:
            - name: XMPP_DOMAIN
              value: {{ .Values.common.domain }}
            - name: XMPP_AUTH_DOMAIN
              value: auth.{{ .Values.common.domain }}
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.{{ .Values.common.domain }}
            - name: XMPP_MUC_DOMAIN
              value: muc.{{ .Values.common.domain }}
            - name: XMPP_GUEST_DOMAIN
              value: guest.{{ .Values.common.domain }}
            - name: JVB_ADMINS
              value: "\"jvb@auth.{{ .Values.common.domain }}\",\"focus@auth.{{ .Values.common.domain }}\""

            - name: JVB_AUTH_USER
              value: {{ .Values.jvb.userAuth.name }}
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "jitsi-meet.name-jvb" . }}-secret
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_USER
              value: {{ .Values.jicofo.userAuth.name }}
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "jitsi-meet.name-jicofo-secret" . }}
                  key: JICOFO_AUTH_PASSWORD
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "jitsi-meet.name-jicofo-secret" . }}
                  key: JICOFO_COMPONENT_SECRET
            - name: AUTH_TYPE
              value: {{ .Values.prosody.userAuth.type | quote }}

            {{- range .Values.prosody.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.common.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - name: xmpp-client
              containerPort: 5222
              protocol: TCP

            - name: xmpp-server
              containerPort: 5269
              protocol: TCP

            - name: xmpp-bosh
              containerPort: 5280
              protocol: TCP

            - name: xmpp-bosh-ssl
              containerPort: 5281
              protocol: TCP

            - name: prosody-compreg
              containerPort: 5347
              protocol: TCP
          resources:
            {{- toYaml .Values.prosody.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/defaults/prosody.cfg.lua"
              subPath: "prosody.cfg.lua"
            - name: config
              mountPath: "/defaults/conf.d/jitsi-meet.cfg.lua"
              subPath: "jitsi-meet.cfg.lua"
            # - name: config
            #   mountPath: "/defaults/conf.d/turn.cfg.lua"
            #   subPath: "turn.cfg.lua"
            - name: config
              mountPath: "/entrypoint.sh"
              subPath: "entrypoint.sh"

      volumes:
        - name: config
          configMap:
            name: {{ template "jitsi-meet.name-prosody" . }}-config
        {{ if .Values.prosody.recorder }}
        - name: shm
          hostPath:
            path: /dev/shm
        - name: dev-snd
          hostPath:
            path: /dev/snd
        {{ end }}
      {{- with .Values.prosody.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.prosody.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.prosody.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
