{{- if (eq .Values.ingress.type "nginx-ingress-disabled") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  # name configured with ingress-nginx helm template
  name: ingress-nginx-tcp
  namespace: {{ .Values.namespace }}
data:
  4443: "jitsi/jitsi-otc-jvb-0:4443"
  9090: "jitsi/jitsi-otc-jvb-0:9090"
{{- end -}}
