apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.name-turn" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  type: {{ .Values.prosody.service.type }}
  ports:
    - name: turn
      port:  {{ .Values.turn.listeningport }}
      targetPort: turn
      protocol: TCP
  ports:
    - name: udp
      port:  {{ .Values.turn.minPort }}
      targetPort: udp
      protocol: UDP

  sessionAffinity: ClientIP
  selector:
    app.kubernetes.io/name: {{ include "jitsi-meet.name-turn" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
status:
  loadBalancer: {}
