apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "jitsi-meet.name-turn" . }}-gw
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  selector:
    istio: ingressgateway #! use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: http2
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: wildcard-tls
    hosts:
    - {{ .Values.turn.turnHost }}
