{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: ingress-nginx
data:
  9090: "jitsi/jitsi-udp-test:9090"  
  10000: "jitsi/jitsi-otc-jvb-0:10000"
{{- end -}}  
