{{- if (eq .Values.ingress.type "nginx-ingress-unused") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: {{ .Values.namespace }}
data:
  10000: "jitsi/jitsi-otc-jvb-0:10000"
{{- end -}}
