apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.name-web" . }}-jwt
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4180
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "jitsi-meet.name-web" . }}-jwt
    app.kubernetes.io/instance: {{ .Release.Name }}
