apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.name-web-config" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
data:
  10-config: |-
    {{- .Files.Get "configs/web/10-config" | nindent 4 }}
  config.js: |-
    {{- .Files.Get "configs/web/config.js" | nindent 4 }}
  interface_config.js: |-
    {{- .Files.Get "configs/web/interface_config.js" | nindent 4 }}
  plugin.head.html: |-
    {{- .Files.Get "configs/web/plugin.head.html" | nindent 4 }}
  welcomePageAdditionalContent.html: |-
    {{- .Files.Get "configs/web/welcomePageAdditionalContent.html" | nindent 4 }}
