apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "jitsi-meet.name-web" . }}-gw
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  selector:
    istio: ingressgateway #! use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - "www.jitsi.otcdemo.gardener.t-systems.net"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: wildcard-tls
    hosts:
    - "www.jitsi.otcdemo.gardener.t-systems.net"