apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.name-web" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jitsi-meet.name-web" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jitsi-meet.name-web" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "jitsi-meet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "jitsi-meet.name-web" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
# we are loading the file so no more editing possible
#          lifecycle:
#            postStart:
#              exec:  # try to fix the error in the image
#                command: ["/bin/sh", "-c", "sed -i 's/cp \\/defaults\\/config.js/tpl \\/defaults\\/config.js >/' /etc/cont-init.d/10-config"]
          env:
            - name: XMPP_DOMAIN
              value: {{ .Values.common.domain }}
            - name: XMPP_AUTH_DOMAIN
              value: auth.{{ .Values.common.domain }}
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.{{ .Values.common.domain }}
            - name: XMPP_MUC_DOMAIN
              value: muc.{{ .Values.common.domain }}
            - name: XMPP_GUEST_DOMAIN
              value: guest.{{ .Values.common.domain }}

            - name: PUBLIC_URL
              value: "https://{{ .Values.webHost }}"
            - name: XMPP_SERVER
              value: {{ include "jitsi-meet.name-prosody" . }}

            - name: JICOFO_AUTH_USER
              value: {{ .Values.jicofo.userAuth.name }}
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "jitsi-meet.name-jicofo-secret" . }}
                  key: JICOFO_AUTH_PASSWORD
            - name: JVB_AUTH_USER
              value: {{ .Values.jvb.userAuth.name }}
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "jitsi-meet.name-jvb-secret" . }}
                  key: JVB_AUTH_PASSWORD
            # to proxy bosh and websockets  (now moved to ingress)
            - name: XMPP_BOSH_URL_BASE
              value: "http://{{ include "jitsi-meet.name-prosody" . }}:5280"
            {{- range .Values.web.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.prosody.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.common.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: http2
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/etc/cont-init.d/10-config"
              subPath: "10-config"
            - name: config
              mountPath: "/defaults/config.js"
              subPath: "config.js"
            - name: config
              mountPath: "/defaults/interface_config.js"
              subPath: "interface_config.js"
            - name: config
              mountPath: "/usr/share/jitsi-meet/plugin.head.html"
              subPath: "plugin.head.html"
            - name: config
              mountPath: "/usr/share/jitsi-meet/welcomePageAdditionalContent.html"
              subPath: "welcomePageAdditionalContent.html"
      volumes:
        - name: config
          configMap:
            name: {{ template "jitsi-meet.name-web-config" . }}
            defaultMode: 0777
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
