apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.name-web" . }}
  namespace: {{ .Values.namespace }}
  labels:  
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "jitsi-meet.name-web" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      
    # # ssl is handled by istio so this is not used externally
    - name: http2
      port: {{ .Values.web.service.sslport }}
      targetPort: http2
      protocol: TCP
