apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.name-web" . }}-svc
  namespace: {{ .Values.namespace }}
  labels:  
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
#  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      
    # ssl is handled by istio
    # - port: {{ .Values.web.service.sslport }}
    #   targetPort: https
    #   protocol: TCP
    #   name: https
  selector:
    app.kubernetes.io/name: {{ include "jitsi-meet.name-web" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
