{{- $basename := include "jitsi-meet.name-web" . }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $basename }}-vs
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  hosts:
  - {{ .Values.webHost }}
  gateways:
  - {{ include "jitsi-meet.name-gateway-fqdn" . }}
# web server  
  http:
#---------------------------------------------------    
  - name: "favicon_remap"
    match:
    - uri:
        prefix: /favicon.ico
    rewrite:
      uri: "/images/favicon.ico"
    route:
    - destination:
        host: {{ include "jitsi-meet.name-websvc-fqdn" . }}
        port:
          number: {{ .Values.web.service.port }}
#---------------------------------------------------
  - name: "standard"
    match:
    - uri:
        regex: /.*
    route:
    - destination:
        host: {{ include "jitsi-meet.name-websvc-fqdn" . }}
        port:
          number: {{ .Values.web.service.port }}
#---------------------------------------------------          
#   - name: "remap-xmpp"
#     match:
#     - uri:
#         prefix:  /xmpp-websocket
#     route:
#     - destination:
#         host: {{ include "jitsi-meet.name-prosody" . }}
#         port:
#           number: 5280
# #    websocketUpgrade: true
#     corsPolicy:
#       allowOrigin:
#       - "*"
#       allowMethods:
#       - POST
#       - GET
#       - OPTIONS
#       - CONNECT
#       allowCredentials: true
#       allowHeaders:
#         - Accept
#         - Accept-Encoding
#         - Accept-Language
#         - Cache-Control
#         - Connection
#         - Cookie
#         - Host
#         - Origin
#         - Pragma
#         - Sec-Websocket-Extensions
#         - Sec-Websocket-Key
#         - Sec-Websocket-Version
#         - Upgrade
#         - Upgrade-Insecure-Requests
#         - User-Agent
#       maxAge: "24h"
