apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "jitsi-meet.name-web" . }}-vs
  namespace: {{ .Values.namespace }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
spec:
  hosts:
  - {{ .Values.webHost }}
  gateways:
  - {{ include "jitsi-meet.name-web" . }}-gw
# lets try tcp protocol
  # tcp:
  # - name: "separate-xmpp"
  #   match:
  #   - uri:
  #       regex: /http-bind.*
  #   route:
  #   - destination:
  #       host: {{ include "jitsi-meet.name-prosody" . }}
  #       port:
  #         number: 5280
# web server  
  http:
  - name: "favicon remap"
    match:
    - uri:
        prefix: /favicon.ico
    rewrite:
      uri: "/images/favicon.ico"
    route:
    - destination:
        host: {{ include "jitsi-meet.name-web" . }}-svc
        port:
          number: {{ .Values.web.service.port }}

  - name: "standard"
    match:
    - uri:
        regex: /.*
    route:
    - destination:
        host: {{ include "jitsi-meet.name-web" . }}-svc
        port:
          number: {{ .Values.web.service.port }}

# video bridge
  # tcp:
  # - match:
  #   - port: {{ .Values.jvb.udpport }}
  #   route:
  #   - destination:
  #       host: {{ include "jitsi-meet.name-jvb" . }}-svc
  #       port:
  #         number: {{ .Values.jvb.udpport }}
  
  # - match:
  #   - port: {{ .Values.jvb.tcpport }}
  #   route:
  #   - destination:
  #       host: {{ include "jitsi-meet.name-jvb" . }}-svc
  #       port:
  #         number: {{ .Values.jvb.tcpport }}
# iterate over replica and assing different ports
{{- $root := . }}
{{- $name := include "jitsi-meet.name-jvb" $root }}
{{- range $index, $nbr := until (.Values.prosody.replicaCount | int) }}
{{- $target := printf "%s-%d" $name $nbr}}
{{- $udpport := printf "%d" (add $root.Values.jvb.baseport $nbr) }}
{{- $tcpport := printf "%d" (add $root.Values.jvb.baseport $root.Values.jvb.tcpoffset $nbr) }}
  - match:
    - port:  {{ atoi $udpport }}
    route:
    - destination:
        host: {{ $target }}
        port:
          number: {{ atoi $udpport }}

  - match:
    - port: {{ atoi $tcpport }}
    route:
    - destination:
        host: {{ $target }}
        port:
          number: {{ atoi $tcpport }}
{{- end }}